name: Deploy to env

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v3
        with:
          version: "latest" # default is latest stable
          id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:
          aws-secret-access-key:
          aws-region: us-west-2

      - name: Update kube config
        run: aws eks update-kubeconfig --name eks-cluster-test --region us-west-2

      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f nginx-pod.yml
          kubectl apply -f nginx-service.yaml
          kubectl port-forward nginx-pod 8080:80
          kubectl apply -f nginx-replicaset.yml
          kubectl apply -f nginx-deployment.yml
          kubectl apply -k kustomization.yml
